/*
 * Copyright (C) 2016 ayron
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fur.shadowdrake.minecraft.bootloader;

import fur.shadowdrake.minecraft.Configuration;
import fur.shadowdrake.minecraft.CredentialDialog;
import fur.shadowdrake.minecraft.ProxyAddress;
import fur.shadowdrake.minecraft.LafList;
import java.awt.Window;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.net.PasswordAuthentication;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ayron
 */
public class InitialConfig extends javax.swing.JDialog {

    private boolean result;
    private ActionListener listener;
    private File installDir;
    private PasswordAuthentication httpProxyCredentials;
    private PasswordAuthentication ftpProxyCredentials;
    private final Configuration config;

    /**
     * Creates new form ProxyConfig
     *
     * @param parent
     * @param modal
     * @param config
     */
    public InitialConfig(java.awt.Frame parent, boolean modal,
            Configuration config) {
        super(parent, modal);
        this.result = false;
        initComponents();
        this.config = config;
        this.installDir = config.getInstallDir();
        this.dirBox.setText(installDir.getAbsolutePath());
        this.httpProxy.setText(config.getHttpProxy());
        this.ftpProxy.setText(config.getFtpProxy());
        this.ftpProxyMode.setSelectedIndex(config.getFtpProxyMode());
        this.httpProxyCredentials = config.getHttpProxyCredentials();
        this.ftpProxyCredentials = config.getFtpProxyCredentials();
        this.httpForFtp.setSelected(config.isHttpForFtp());
        httpForFtpActionPerformed(null);
        this.laf.setSelectedItem(config.getLaf());
        setLocationRelativeTo(null);
    }

    public File getInstallDir() {
        return installDir;
    }

    public String getHttpProxy() {
        return httpProxy.getText();
    }

    public String getFtpProxy() {
        return ftpProxy.getText();
    }

    public PasswordAuthentication getHttpProxyCredentials() {
        return httpProxyCredentials;
    }

    public PasswordAuthentication getFtpProxyCredentials() {
        return ftpProxyCredentials;
    }

    public int getFtpProxyMode() {
        return ftpProxyMode.getSelectedIndex();
    }

    public String getLaf() {
        return (String) laf.getSelectedItem();
    }

    public void setActionListener(ActionListener listener) {
        this.listener = listener;
    }

    public boolean getResult() {
        return result;
    }

    public boolean isHttpForFtp() {
        return httpForFtp.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proceed = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dirBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        httpProxy = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ftpProxy = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ftpProxyMode = new javax.swing.JComboBox<>();
        dirBrowse = new javax.swing.JButton();
        httpLogin = new javax.swing.JButton();
        ftpLogin = new javax.swing.JButton();
        httpForFtp = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        laf = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Initial config");
        setResizable(false);

        proceed.setText("Proceed");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(dirBox);
        jLabel1.setText("Install directory");

        dirBox.setToolTipText("Will be created if not existent.");

        jLabel2.setLabelFor(httpProxy);
        jLabel2.setText("http proxy");

        httpProxy.setToolTipText("Empty means direct. Port defaults to 3128.");
        httpProxy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                httpProxyKeyPressed(evt);
            }
        });

        jLabel3.setLabelFor(ftpProxy);
        jLabel3.setText("ftp proxy");

        ftpProxy.setToolTipText("Empty means direct. Port defaults to 2121.");
        ftpProxy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftpProxyKeyPressed(evt);
            }
        });

        jLabel4.setLabelFor(ftpProxyMode);
        jLabel4.setText("ftp proxy mode");

        ftpProxyMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user@host", "SITE host", "OPEN host" }));
        ftpProxyMode.setToolTipText("choose user@host if you use ftp.proxy");

        dirBrowse.setText("Browse");
        dirBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirBrowseActionPerformed(evt);
            }
        });

        httpLogin.setText("Login");
        httpLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                httpLoginActionPerformed(evt);
            }
        });

        ftpLogin.setText("Login");
        ftpLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftpLoginActionPerformed(evt);
            }
        });

        httpForFtp.setText("use http proxy for ftp");
        httpForFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                httpForFtpActionPerformed(evt);
            }
        });

        jLabel5.setText("Design");

        laf.setModel(new LafList());
        laf.setToolTipText("If you want the default design, select Metal. (Nimbus on Solaris)");
        laf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lafActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(httpForFtp)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(laf, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dirBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(httpProxy, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftpProxy, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftpProxyMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dirBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(httpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ftpLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(proceed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dirBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(httpProxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(httpLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftpProxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftpLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftpProxyMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(httpForFtp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceed)
                    .addComponent(exit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void httpLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_httpLoginActionPerformed
        CredentialDialog credentials = new CredentialDialog(new JFrame(), true, httpProxyCredentials, "http proxy credentials.");
        credentials.setVisible(true);
        if (credentials.getReturnStatus()) {
            httpProxyCredentials = credentials.getAuthentication();
        }
        credentials.dispose();
    }//GEN-LAST:event_httpLoginActionPerformed

    private void lafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lafActionPerformed
        LafList lafList = (LafList) laf.getModel();
        try {
            UIManager.setLookAndFeel(lafList.get((String) laf.getSelectedItem()));

            Window[] exc = Window.getWindows();
            int wasVisible = exc.length;

            for (int i$ = 0; i$ < wasVisible; ++i$) {
                Window window = exc[i$];
                SwingUtilities.updateComponentTreeUI(window);
                window.pack();

                if (window instanceof JDialog) {
                    JDialog frame = (JDialog) window;
                    boolean wasDecoratedByOS = !frame.isUndecorated();
                    boolean var8 = UIManager.getLookAndFeel().getSupportsWindowDecorations();
                    if (var8 == wasDecoratedByOS) {
                        frame.setVisible(false);
                        frame.dispose();
                        if (var8) {
                            frame.setUndecorated(true);
                            frame.getRootPane().setWindowDecorationStyle(2);
                        } else {
                            frame.setUndecorated(false);
                            frame.getRootPane().setWindowDecorationStyle(0);
                        }

                        frame.setVisible(true);
                        if (frame instanceof InitialConfig) {
                            frame.setSize(getPreferredSize());
                        }
                    }
                }
            }

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lafActionPerformed

    private void dirBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirBrowseActionPerformed
        JFileChooser fc = new JFileChooser(new File(dirBox.getText()));

        fc.setFileHidingEnabled(false);
        fc.setDialogTitle("Select directory");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            dirBox.setText(fc.getSelectedFile().toString());

        }
    }//GEN-LAST:event_dirBrowseActionPerformed

    private void ftpLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftpLoginActionPerformed
        CredentialDialog credentials = new CredentialDialog(new JFrame(), true, ftpProxyCredentials, "ftp proxy credentials");
        credentials.setVisible(true);
        if (credentials.getReturnStatus()) {
            ftpProxyCredentials = credentials.getAuthentication();
        }
        credentials.dispose();
    }//GEN-LAST:event_ftpLoginActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        /* quick check */
        ProxyAddress addr;

        installDir = new File(dirBox.getText());
        if (!installDir.exists() && !installDir.mkdirs()) {
            JOptionPane.showMessageDialog(this, "Can't create install directory.");
            return;
        }

        try {
            if (!httpProxy.getText().isEmpty()) {
                addr = new ProxyAddress(httpProxy.getText(), 3128);
            }
            if (!ftpProxy.getText().isEmpty()) {
                addr = new ProxyAddress(ftpProxy.getText(), 2121);
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "Proxy must be in format \"host:port\"\nEg. rayquaza.yiff-me.eu:3128 or 192.168.0.1:3128\nWhen the port is omitted, the default port is used.");
            return;
        }

        config.setInstallDir(installDir);
        config.setHttpProxy(httpProxy.getText());
        config.setHttpProxyCredentials(httpProxyCredentials);
        config.setFtpProxy(ftpProxy.getText());
        config.setHttpForFtp(httpForFtp.isSelected());
        config.setLaf((String) laf.getSelectedItem());
        setVisible(false);
        result = true;
        if (listener != null) {
            listener.actionPerformed(evt);
        }
    }//GEN-LAST:event_proceedActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        setVisible(false);
        result = false;
        if (listener != null) {
            listener.actionPerformed(evt);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void ftpProxyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftpProxyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            JOptionPane.showMessageDialog(this, "Proxy must be in format \"host[:port]\"\nEg. groudon.yiff-me.eu:2121 or 192.168.0.2:2121\nWhen the port is omitted, the default port (2121) is used.");
        }
    }//GEN-LAST:event_ftpProxyKeyPressed

    private void httpProxyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_httpProxyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            JOptionPane.showMessageDialog(this, "Proxy must be in format \"host[:port]\"\nEg. kyogre.yiff-me.eu:3128 or 192.168.0.1:3128\nWhen the port is omitted, the default port (3128) is used.");
        }
    }//GEN-LAST:event_httpProxyKeyPressed

    private void httpForFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_httpForFtpActionPerformed
        ftpProxy.setEnabled(!httpForFtp.isSelected());
        ftpLogin.setEnabled(!httpForFtp.isSelected());
    }//GEN-LAST:event_httpForFtpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dirBox;
    private javax.swing.JButton dirBrowse;
    private javax.swing.JButton exit;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton ftpLogin;
    private javax.swing.JTextField ftpProxy;
    private javax.swing.JComboBox<String> ftpProxyMode;
    private javax.swing.JCheckBox httpForFtp;
    private javax.swing.JButton httpLogin;
    private javax.swing.JTextField httpProxy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> laf;
    private javax.swing.JButton proceed;
    // End of variables declaration//GEN-END:variables
}
