/*
 * Copyright (C) 2016 ayron
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fur.shadowdrake.minecraft.bootloader;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.JScrollBar;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author ayron
 */
public class JavaConsole extends javax.swing.JFrame {

    private boolean release;
    private final PrintStream stdout;
    private final PrintStream stderr;

    /**
     * Creates new form LogWindow
     */
    public JavaConsole() {
        initComponents();
        PrintStream ps = new PrintStream(new OutputStream() {
            @Override
            public void write(int b) throws IOException {
                byte[] x = new byte[1];
                x[0] = (byte) b;
                print(new String(x));
            }

            @Override
            public void write(byte[] b, int off, int len) throws IOException {
                print(new String(b, off, len));
            }

            @Override
            public void close() throws IOException {
                System.setErr(stderr);
                System.setOut(stdout);
                dispose();
            }
        });
        stdout = System.out;
        stderr = System.err;
        System.setErr(ps);
        System.setOut(ps);
        release = false;
    }

    public void println(String text) {
        print(text + "\n");
    }

    public void print(String text) {
        Document document = this.logBox.getDocument();
        final JScrollBar scrollBar = this.jScrollPane1.getVerticalScrollBar();

        try {
            document.insertString(document.getLength(), text, (AttributeSet) null);
        } catch (BadLocationException ex) {
        }
        java.awt.EventQueue.invokeLater(() -> {
            scrollBar.setValue(Integer.MAX_VALUE);
        });
    }

    public void setRelease(boolean release) {
        this.release = release;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Java Console");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        logBox.setEditable(false);
        logBox.setColumns(20);
        logBox.setRows(5);
        jScrollPane1.setViewportView(logBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (release) {
            System.exit(0);
        } else {
            setState(ICONIFIED);
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logBox;
    // End of variables declaration//GEN-END:variables
}
